### ISSUE TITLE
Improve error response on mcs misuse

### ISSUE THREAD

**Issue by BranislavBeno** [mthmulders/mcs#157]
Error response currently exposes stacktrace (see attached screenshot).
![mcs-exception](https://user-images.githubusercontent.com/57846939/206897297-64cb9d51-a2e8-4c38-9451-16bbd8614ce0.png)

Due to security concerns mitigation, stacktrace should not be part of error message showed to user.

**Comment by mthmulders** [comment]
Fixed in d7fbf8e.
