### ISSUE TITLE
Make the command 'search' the default command

### ISSUE THREAD

**Issue by mthmulders** [mthmulders/mcs#18]
As `mcs` stands for "Maven Central Search", it's a bit odd to type `mcs search foo`. It would be great if one could type `mcs foo` and MCS would know it's supposed to run the "search" command with "foo" as a parameter.

Given the [ideas for further development](https://github.com/mthmulders/mcs/blob/main/README.md#ideas-for-future-development), it's important to take into account that later, `mcs` may have more than one command. Imagine there's a `copy` command, it's important to distinguish between `mcs search foo` and `mcs copy`. The latter is _not_ `mcs search copy` but `mcs copy` (probably with a missing parameter, who knows?)

**Comment by shaikhu** [comment]
Hi @mthmulders 👋 , so I've been thinking of an approach for this and came up with an idea. Would appreciate your thoughts on this draft [PR](https://github.com/mthmulders/mcs/pull/289). Worth pursing or not? 

It's also worth mentioning, the approach in the PR is **not** backwards compatible. Is that a deal breaker for you? While it is possible to support both `mcs search foo` and `mcs  foo`, it involved a lot of duplicate code, (copying parameters/options) between `SearchCommand` and the top level class. Was kind of messy.

**Comment by mthmulders** [comment]
Released in [MCS 0.6.0](https://github.com/mthmulders/mcs/releases/tag/v0.6.0).
