### ISSUE TITLE
No results in company network with TLS interception

### ISSUE THREAD

**Issue by frimtec** [mthmulders/mcs#194]
In our company we have a TLS interception.
Therefore mcs can't connect to the backend as of a certificate issue.
The result is just empty result, but no error is displayed.

How can the certificate truststore can be configured?
Setting it via ```-Djavax.net.ssl.trustStrore=company-ca.jks``` seems not to work.

**Comment by mthmulders** [comment]
Hi @frimtec, thanks for reporting this!

>  The result is just empty result, but no error is displayed.

Oh, that's not nice. It should at least give you a clue as to why it didn't work.

> How can the certificate truststore can be configured?

I'll have to investigate. I distribute MCS as a native executable - it probably requires some fiddling to pass a custom truststore.

**Comment by mthmulders** [comment]
The latest [_early-access_ build](https://github.com/mthmulders/mcs/releases/tag/early-access) should have this problem addressed - at least MCS should show you what went wrong. @frimtec, could you please verify that you get a meaningful error message with that build?

**Comment by frimtec** [comment]
Hi @mthmulders 

Thanks, not I see a error message:
```
frim@:/c/Develop/tools/mcs-0.3.2-SNAPSHOT-windows-x86_64/bin> ./mcs.exe search jpse
Searching for jpse...
java.net.ConnectException
```

**Comment by mthmulders** [comment]
Thanks for confirming, @frimtec. I've enhanced the display of the error message a bit.

For now, I will close this issue, as #199 at least ensures you'll get some kind of error message. In the meantime, I'll figure out how to work with custom trust stores - that work is tracked in #195. That will probably take a bit more time. I'll make sure to ship a release with this improvement in error handling shortly!

**Comment by mthmulders** [comment]
@all-contributors please add @frimtec for bug.
