### ISSUE TITLE
Known vulnerabilities

### ISSUE THREAD

**Issue by bmarwell** [mthmulders/mcs#22]
Show an artifact as vulberable or as vulberable in Dependencies (except test dependencies).

Maybe a hint coloured red and yellow.

**Comment by mthmulders** [comment]
This is a very interesting and relevant idea - thanks for sharing it. If I recall correctly from a Twitter convo, it's inspired by the fact that [mvnrepository.com](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core/2.17.0) displays it. I've taken a look at how they do it, and it seems to me they do a lookup server side and then include it in the HTML that they send to the browser.

I'd rather not use web page scraping to collect this information. @bmarwell, do you happen to know any (REST-like) API which could give the same information?

**Comment by mthmulders** [comment]
Result pages on search.maven.org provide a link to the Sonatype OSS index (e.g. [log4j-core](https://ossindex.sonatype.org/component/pkg:maven/org.apache.logging.log4j/log4j-core@2.17.0)) but that suffers from the same issue: it only serves the response in a full-fledged HTML page :-(.

**Comment by bmarwell** [comment]
I don't know of a REST-API, sorry.

**Comment by AbdelHajou** [comment]
Hey @mthmulders , the link to the Sonatype website you provided has another link to their [REST API](https://ossindex.sonatype.org/rest) at the bottom of the page. The api/v3/component-report endpoint returns a list of vulnerabilities for the component with this coordinate. 

![image](https://user-images.githubusercontent.com/62144407/154492437-4ac1c34d-7553-44fe-b7cc-8c86baf8778a.png)

I haven't looked much further into this API, but if you agree I could look into this issue and maybe implement it when I have time.

**Comment by mthmulders** [comment]
Good catch, @AbdelHajou. I'm definitely going to investigate that route. Their [documentation](https://ossindex.sonatype.org/doc/rest) also says 

>  Rate limits apply to requests. If the rate is exceeded then responses will indicate 429 Too many requests status.
Authenticated requests have a higher limit.

They don't mention the exact limit, though. 

Maybe **mcs** could do unauthenticated requests by default. Additionally, it could have support for people who want to use their Sonatype account so they can do _more_ requests. But that requires a bit of thinking (how/where to store those credentials, how to fall back if there are none, etc.).

Additionally, **mcs** might only include security info using this Sonatype API when the user explicitly asks for it, e.g. using a flag.

**Comment by mthmulders** [comment]
@all-contributors please add @AbdelHajou for idea.
