### ISSUE TITLE
Enhancement: Make plugins more copy friendly

### ISSUE THREAD

**Issue by Giovds** [mthmulders/mcs#232]
I wanted to version lock some plugins in my `pom.xml` and I used `mcs` to search for the latest version.
After finding the latest version you get the following response:

```xml
<dependency>
   ...omitted for brevity...
</dependency>
```

Would it make sense (in most cases) for plugins to suggest the following?

```xml
<plugin>
...omitted for brevity...
</plugin>
```

The response from central [already contains](https://central.sonatype.org/search/rest-api-guide/#:~:text=Mimics%20searching%20by%20coordinate%20in%20Advanced%20Search.%20This%20search%20uses%20all%20coordinates%20(%22g%22%20for%20groupId%2C%20%22a%22%20for%20artifactId%2C%20%22v%22%20for%20version%2C%20%22p%22%20for%20packaging%2C%20%22l%22%20for%20classifier)) (or [an actual response](https://central.sonatype.com/solrsearch/select?q=maven-jar-plugin#:~:text=%22%3A%C2%A0%22-,maven%2Dplugin,-%22%2C)) a value `p` which contains the packaging type, which could be used to check if it is a `maven-plugin`.

Happy to create a PR, let me know!

**Comment by mthmulders** [comment]
Sorry for the delayed response. I like this idea a lot :-) I'd love to see a PR for this!

Please note that @hannotify and I started working on #192. I do not expect it to be finished overnight, but it may affect the way classes are constructed. If you expect you can do this change without touching much of the relations between classes, you're probably not going to be hindered anyway.
