### ISSUE TITLE
Allow non-trusted cert paths

### ISSUE THREAD

**Issue by DarekDan** [mthmulders/mcs#235]
Common problem for ZScaler users, or any other proxy with custom CA certs:

```
➜  CertExtract mcs class-search CommandLine                                                                                              
Searching for artifacts containing CommandLine...
MCS ran into an error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

If the error persist, please consider reporting the issue at https://github.com/mthmulders/mcs/issues/new
```

**Comment by mthmulders** [comment]
Hi @DarekDan, I don't know what `CertExtract` is or does.

As as far as I know, you should be able to specify the trust store for MCS using `-Djavax.net.ssl.trustStore=/path/to/keystore`. This was confirmed in #195 by another user, and in the meantime, I have been able to confirm this myself as well. Can you see if this works for you, too?

I just haven't found the time yet to update the documentation for it 😐

**Comment by DarekDan** [comment]
100% correct. Thanks for the quick guidance.
