### ISSUE TITLE
Add chocolatey deployment

### ISSUE THREAD

**Issue by jeffmaury** [mthmulders/mcs#25]

**Comment by mthmulders** [comment]
I'm happy to report that a Chocolatey package is already in progress. The package is not yet listed publicly (pending review / approval, I don't know the exact procedure) but you can already install it: https://community.chocolatey.org/packages/mcs. Once it is publicly listed, I'll update the README.

**Comment by mthmulders** [comment]
Forgot to mention: as long as the package isn't publicly listed, you should explicitly specify the version:

```cmd
choco install mcs --version 0.1.18
```

**Comment by mthmulders** [comment]
The Chocolatey [mcs package](https://community.chocolatey.org/packages/mcs) is now "approved", meaning users can run `choco install mcs`.

**Comment by mthmulders** [comment]
@all-contributors please add @jeffmaury for idea.
