### ISSUE TITLE
search and show command

### ISSUE THREAD

**Issue by bmarwell** [mthmulders/mcs#30]
```
mcs search ch.qos.logback:logback-classic
```

If it outputs an xml snipped, maybe `mcs show` would be the better subcommand name.

Rationale: Maybe I want to use it with `--last` from a specific version on-/downgoing, see https://github.com/mthmulders/mcs/issues/21.

**Comment by mthmulders** [comment]
Thanks for the input. I've moved this to a [discussion](https://github.com/mthmulders/mcs/discussions/32) because I'd love to hear/collect some more ideas before implementing this.

**Comment by mthmulders** [comment]
@all-contributors please add @bmarwell for idea.
