### ISSUE TITLE
MCS ran into an error: null

### ISSUE THREAD

**Issue by jwedel** [mthmulders/mcs#363]
Hi,

just installed MCS via brew on my Mac M1. After successful installation, I ran:

```
➜ mcs search plexus-utils
Searching for plexus-utils...
MCS ran into an error: null

If the error persist, please consider reporting the issue at https://github.com/mthmulders/mcs/issues/new
```

One potential thing: Does mcs supports proxies? Like does it respect the `HTTP[S]_PROXY` env variable as I am behind a corporate proxy?

**Comment by mthmulders** [comment]
Hi Jan, thanks for giving MCS a try!

MCS uses the default HTTP client that ships with the JDK (`java.net.http` package). I don't think that one respects the `HTTP[S]_PROXY` env variables, but it does respect JVM settings such as `java.net.useSystemProxies` or `http.proxyHost`, `http.proxyPort` and their https counterparts.

Do you suspect the issue might be related to MCS not using a proxy server while you expect it too? In that case, at least it should give a better error message than just `null`.

If you feel comfortable with it, can you try running MCS from an IDE? If you could put a breakpoint in line 36 of `SearchClient`, it should tell you the exception it found there. Another useful point could be line 8 of `McsExecutionExceptionHandler`, as that's where the exception gets printed to output.

**Comment by jwedel** [comment]
This is what I can see:
![image](https://github.com/mthmulders/mcs/assets/4849728/389bea56-0486-47d4-a252-6b2fb985367e)

It is most probably due the missing proxy usage. The DNS will not resolve external host names. You have to use the proxy.

I tried the Java setting `-Dhttp.proxyHost=localhost -Dhttp.proxyPort=3128` but it still fails.

**Comment by mthmulders** [comment]
Thanks, Jan, that is very useful information! I'll make sure to give a (slightly) better error in that case.

> I tried the Java setting `-Dhttp.proxyHost=localhost -Dhttp.proxyPort=3128` but it still fails.

You could try `-Dhttps.proxyHost=localhost -Dhttps.proxyPort=3128` as MCS uses HTTPS rather than HTTP.

**Comment by jwedel** [comment]
> You could try `-Dhttps.proxyHost=localhost -Dhttps.proxyPort=3128` as MCS uses HTTPS rather than HTTP.

Yeah, that works!

So, although that works, it would be great if the tool could respect the env variables.

**Comment by mthmulders** [comment]
> > You could try `-Dhttps.proxyHost=localhost -Dhttps.proxyPort=3128` as MCS uses HTTPS rather than HTTP.
> 
> Yeah, that works!

Great!

> So, although that works, it would be great if the tool could respect the env variables.

Agreed! I've logged #368 to track that. Are there more proxy-related environment variables that come into play?

**Comment by mthmulders** [comment]
[v0.6.4](https://github.com/mthmulders/mcs/releases/tag/v0.6.4) should at least provide you a more meaningful error message.
