### ISSUE TITLE
Support mac m1 platform

### ISSUE THREAD

**Issue by spencergibb** [mthmulders/mcs#57]
I have no idea if it is even possible.

**Comment by mthmulders** [comment]
Thanks for reaching out! It's definitely something I'd like to see happening! The **mcs** executables are produced with [GraalVM's native-image](https://www.graalvm.org/22.0/reference-manual/native-image/) tool. To the best of my knowledge, this does not (yet) work for Apple Silicon; https://github.com/oracle/graal/issues/2666 seems to track progress on this.

In the meantime, I have received some reports about users using **mcs** on top of Rosetta.

**Comment by spencergibb** [comment]
Looks like it is close. Guess I need to see how I can install/run cli tools with rosetta in the meantime.

**Comment by mthmulders** [comment]
Fixed as of [v0.2.2](https://github.com/mthmulders/mcs/releases/tag/v0.2.2)!

**Comment by spencergibb** [comment]
awesome! works great

**Comment by mthmulders** [comment]
@all-contributors please add @spencergibb for idea.
